title: Service04
default_lang: ru
author:
  name: Korolewww
  email: s89262211348@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Срочный ремонт газовых и электрических котлов в Москве и МО. Выезд мастера на дом 24/7. Диагностика, чистка и устранение неисправностей. Гарантия до 2 лет.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
