enabled: true
production-mode: true
grid-size: grid-lg
header-fixed: true
header-animated: true
header-dark: false
header-transparent: true
sticky-footer: true
blog-page: /blog
spectre:
  exp: true
  icons: true
custom_logo:
  user/themes/quark/images/logo/unnamed.jpg:
    name: unnamed.jpg
    type: image/jpeg
    size: 90265
    path: user/themes/quark/images/logo/unnamed.jpg
custom_logo_mobile: {  }
custom_css: true
